### ISSUE TITLE
GlobalContextsController won't accept falsey values

### ISSUE THREAD

**Issue by elliotmassen** [opendialogai/opendialog#102]
When attempting to set a global attribute with a falsey value such as `0`, it fails validation. It seems also that the return type mismatch when returning an error causes an internal server error too.

https://github.com/opendialogai/opendialog/blob/a2bf1e2029c0ede86f601dedc0b212d6c2ba63ab/app/Http/Controllers/API/GlobalContextsController.php#L128-L133

**Comment by stu-greenshoots** [comment]
Update this to check if $globallContext->value isset instead
