### ISSUE TITLE
Conversation Admin APIs inefficient 

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/opendialog#105]
Locally, getting conversations with a call to /conversation?page=1 takes over 10 seconds to complete.

Review what is being returned to top-level calls to get all conversations and whether we can return a subset of this. Also, look at eager loading any relationships that are in use.

We should be able to respond to the API call in a fraction of the current time

**Comment by stu-greenshoots** [comment]
It is returning conversation history which is not needed. We can use the ConversationCollection class to restrict what is returned calls to the index method of ConversationController

**Comment by duncanheron** [comment]
@stu-greenshoots This one can be closed based on https://github.com/opendialogai/opendialog/pull/113
