### ISSUE TITLE
Activating and De-activating conversations that are in draft state

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/opendialog#126]
There is a mismatch between the displayed status and the available actions for a conversation. 

The actions still relate to the status of the most recent version in MySQL, not the graph. It seems we'll need to communicate this better and perhaps add/remove certain elements. See the following screenshot for an example. Conversation #1 is persisted and activated, #2 is persisted and deactivated and #8 is not persisted, yet all of them have activatable drafts as each of their activate buttons reflect.

![image](https://user-images.githubusercontent.com/35454728/73960868-84cd5480-4903-11ea-9313-dd5ed00d9a68.png)

**Comment by rogerioalvesgtr** [comment]
up

**Comment by istos** [comment]
This is dealt with differently in 1.0 so closing this.
