### ISSUE TITLE
lando yarn install

### ISSUE THREAD

**Issue by yleal** [opendialogai/opendialog#140]
Best regards!

I am installing OpenDialog on a doker with Lando, but in the set_up_od.sh installation process there is an instruction that says "lando yarn install", when it gets there the installation is interrupted because the command is not recognized by Lando.

Looking for the documentation, yarn can be installed as a global dependency but it doesn't work, or I'm doing it wrong.

Any comments would be helpful!

**Comment by istos** [comment]
We've put in place a different deployment method - you can follow instructions here: https://github.com/opendialogai/opendialog/tree/develop/docker/od-demo for a quick demo or here: https://github.com/opendialogai/opendialog-dev-environment for a fuller dev environment.
