### ISSUE TITLE
No Such Image : opendialogai/opendialog

### ISSUE THREAD

**Issue by rajeshr6r** [opendialogai/opendialog#155]
Hi,

Getting an error when firing the docker-compose up -d app command 

Environment : UBUNTU 18.04 on AWS  .

Error 

ubuntu@ip-172-31-50-198:~/od-demo/opendialog-develop/docker/od-demo$ docker-compose up -d app
WARNING: The TAG variable is not set. Defaulting to a blank string.
WARNING: The DB_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The DB_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The DB_DATABASE variable is not set. Defaulting to a blank string.
Creating network "oddemo_app-network" with driver "bridge"
Creating volume "oddemo_dbdata" with local driver
Creating volume "oddemo_dgraph" with default driver
Creating volume "oddemo_appdata" with default driver
Pulling dgraph-server (dgraph/dgraph:v1.1.0)...
v1.1.0: Pulling from dgraph/dgraph
6abc03819f3e: Pull complete
05731e63f211: Pull complete
0bd67c50d6be: Pull complete
2f379a822eb5: Pull complete
bd9dcef34075: Pull complete
a393c56788e4: Pull complete
Digest: sha256:d7dc44603826e5f79bbb165c85c016de3b60acc6bf4fbbc778330a589c7babae
Status: Downloaded newer image for dgraph/dgraph:v1.1.0
Pulling db (mysql:5.7.27)...
5.7.27: Pulling from library/mysql
8f91359f1fff: Pull complete
6bbb1c853362: Pull complete
e6e554c0af6f: Pull complete
f391c1a77330: Pull complete
414a8a88eabc: Pull complete
fee78658f4dd: Pull complete
9568f6bff01b: Pull complete
76041efb6f83: Pull complete
ea54dbd83183: Pull complete
566857d8f022: Pull complete
01c09495c6e7: Pull complete
Digest: sha256:f7985e36c668bb862a0e506f4ef9acdd1254cdf690469816f99633898895f7fa
Status: Downloaded newer image for mysql:5.7.27
**ERROR: no such image: opendialogai/opendialog:: invalid reference format**

**Comment by istos** [comment]
Hi @rajeshr6r, sounds like the .env for Docker config was not in place. We've updated the documentation to make that clearer and provide an example. Give it a go now and let me know

https://github.com/opendialogai/opendialog/commit/fc43828a9c4ab271322eb46875005044249ec08f

**Comment by rajeshr6r** [comment]
Hello Ronald,

Thanks so much . WIll check this .

*Rajesh R *

*India : + 91 9819-937-639 *
*rajesh.r6r@gmail.com* <rajesh.r6r@gmail.com>

**Comment by rajeshr6r** [comment]
Hello Ronald,

Just got more issues . I'm using the instructions from here like the last time . 

https://github.com/opendialogai/opendialog/tree/develop/docker/od-demo

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.


ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for networks: 'app-network'
Unsupported config option for volumes: 'dbdata'
Unsupported config option for services: 'dgraph-zero'
