### ISSUE TITLE
failed to open webchat

### ISSUE THREAD

**Issue by rogerioalvesgtr** [opendialogai/opendialog#177]
Failed to load resource: net::ERR_CONNECTION_REFUSED opendialog-bot.js:1

the link to http: //localhost/vendor/webchat/js/opendialog-bot.js, but it should be http: //192.168.254.56/vendor/webchat/js/opendialog-bot.js.

where can i change this?

**Comment by AMASHALA** [comment]
Anyway can assist me with steps how to install opendialog please on Ubuntu

**Comment by istos** [comment]
If anyone is still facing this issue given the new Docker setup instructions in the readme or the OpenDialog dev environment - https://github.com/opendialogai/opendialog-dev-environment please open a new issue.
