### ISSUE TITLE
Issue with docker image 0.7.x & 1.0

### ISSUE THREAD

**Issue by jst84** [opendialogai/opendialog#253]
Hi, I have an issue by using docker images.
By using 1.0 I receive an error message creating a new scenario:
![image](https://user-images.githubusercontent.com/25516048/111334165-9e4adf00-8673-11eb-8f57-bca7b51f2cc6.png)

By using 0.7.x the frontend app container (od-demo_app_1) does not start:
![image](https://user-images.githubusercontent.com/25516048/111334803-292bd980-8674-11eb-85ff-694d26046065.png)

thanks a lot,
Stefano.

**Comment by istos** [comment]
Hey @jst84 1.x is not quite ready for prime time yet so wouldn't expect that to work. 0.7.x docker setup has some issues with PHP7.4 which we hadn't caught. We should have a fix in the next couple of days - thanks for highlighting!

**Comment by istos** [comment]
1.x instructions / setup resolved with #268 - keep in mind that 1.x is still in development so there will be issues for another couple of weeks in the 1.x branch until our final 1.0 release.
