### ISSUE TITLE
deploy on heroku

### ISSUE THREAD

**Issue by ah1me5d04** [opendialogai/opendialog#354]
is there a way to deploy opendialog to **heroku**?

**Comment by istos** [comment]
Hi - yes it is possible to deploy OpenDialog to heroku as long as you setup the environment requirements appropriately - https://docs.opendialog.ai/getting-started-1/installing-opendialog/deployment

You can also follow this guide for deployment through Forge which makes the process a bit simpler - Forge doesn't support Heroku but it gives you a choice of other hosts. 
https://docs.opendialog.ai/getting-started-1/installing-opendialog/deployment/deployment-through-forge

**Comment by ah1me5d04** [comment]
can u please wire a tutorial about that?
i am not good at back-end or DevOps so i won't be able to do it on my own
